config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'welcome#index'
  resources :technology, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :technology
end

app/models/technology.rb
class Technology < ApplicationRecord
  URL_REGEX = /\A(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/?.*)?$)\z/ix.freeze
  has_many :categories
  accepts_nested_attributes_for :categories

  validates_uniqueness_of :repo_url
  validates  :repo_url, format: { with: URL_REGEX, message: "Incorrect url format." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/technology_controller.rb
class TechnologyController < ApplicationController
  def index
    @technologies = Technology.all.includes(:categories)
  end

  def show
    @tech = Technology.find_by(id: params[:id])
  end

  def new
    @tech = Technology.new
    @tech.categories.build
  end

  SubmitQuery = SWAPI::Client.parse <<-'GRAPHQL'
    query ($owner: String!, $name: String!) {
      repository(owner:$owner, name:$name) {
        watchers(last: 2) {
          edges {
            node {
              name
            }
          }
        }
        viewerHasStarred
        stargazerCount
        forkCount
        updatedAt
        forks(last: 2) {
          edges {
            node {
              id
              updatedAt
            }
          }
        }
      }
    }
  GRAPHQL

  def create
    repo_ary = technology_params[:repo_url].split("/")
    repo_result = SWAPI::Client.query(SubmitQuery, variables: {name: repo_ary.last, owner: repo_ary.last(2)[0]})

    @tech = Technology.find_or_create_by({name: technology_params[:name], repo_url: technology_params[:repo_url]})

    if @tech && repo_result
      @tech.star_count = repo_result.data.repository.stargazer_count
      @tech.fork_count = repo_result.data.repository.fork_count
      @tech.last_commit_at = repo_result.data.repository.updated_at
      @tech.save
      category = Category.find_or_create_by({name: technology_params[:categories_attributes]["0"][:name], technology_id: @tech.id})
      redirect_to technology_index_url
    else
      flash.alert = "No record created!"
      render :action => :new
    end
  end

  protected

  def technology_params
    params.require(:technology).permit(:name, :repo_url, categories_attributes: [:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awesomeness</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/technology/index.html.erb
<h2>Technology List</h2>

<table>
  <tr>
    <td>Tech Name</td>
    <td>Category</td>
    <td>Repository URL</td>
    <td>Link</td>
  </tr>
  <% @technologies.each do |tech|%>
  <tr>
    <td><%= tech.name %></td>
    <td><%= tech.categories.pluck(:name).join(",") %></td>
    <td><%= tech.repo_url %></td>
    <td><a href="<%= technology_url(tech) %>">more...</a></td>
  </tr>
<% end %>
</table>

app/views/technology/new.html.erb
<% flash.each do |type, msg| %>
  <div><%= msg %>
<% end %>

<h2>Add New Technology</h2>

<%= form_for @tech, url: technology_index_path do |f| %>
 <div><%= f.label :name %><br/>
   <%= f.text_field :name, autofocus: true %>
 </div>

 <div><%= f.label :category %><br/>
   <%= f.fields_for :categories do |cf| %>
     <%= cf.text_field :name %>
   <% end %>
 </div>

 <div><%= f.label :repo_url %><br/>
   <%= f.text_field :repo_url %>
 </div>

  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/technology/show.html.erb
<% flash.each do |type, msg| %>
  <div><%= msg %>
<% end %>

<h2>Technology Detail of <%= @tech.name %></h2>
<p>Star Count: <%= @tech.star_count %></p>
<p>Fork Count: <%= @tech.fork_count %></p>
<p>Time Eslapsed: <%= DateTime.now.in_time_zone("UTC").to_i - @tech.last_commit_at.to_i %> seconds</p>
<p>Repository URL: <%= @tech.repo_url %></p>